apiVersion: v1
kind: Service
metadata:
  name: keda-http-interceptor
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.interceptor.fqdn }}
  ports:
    - name: proxy
      port: {{ .Values.interceptor.port }}
      targetPort: {{ .Values.interceptor.port }}
