apiVersion: v1
kind: ResourceQuota
metadata:
  name: preview-quota
  labels:
    {{- include "preview.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu | quote }}
    requests.memory: {{ .Values.quota.memory | quote }}
    limits.cpu: {{ .Values.quota.cpu | quote }}
    limits.memory: {{ .Values.quota.memory | quote }}
    pods: {{ .Values.quota.pods | quote }}
