{{- range $i, $c := (include "preview.components" . | fromJson).items }}
{{- if $i }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $c.fullname }}
  labels:
    {{- include "preview.componentLabels" (dict "c" $c "root" $) | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $c.fullname }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $c.port }}
{{- end }}
