# Repos onboarded to team nimat's preview cluster (F020, DEC-050). Adding a repo = one entry here +
# `tofu apply` (identity, roles, GitHub env/vars, k8s guard file) + commit clusters/nimat/config/repos/.
locals {
  repos = {
    todo = {
      repository     = "nimat-dev/ephemeral-environments"
      display_name   = "gh-preview-deployer" # created by a5 before per-repo naming
      image_name     = "todo"
      preview_domain = "preview.nimat.dev"
      federated_subjects = {
        gh-preview-env           = "repo:nimat-dev/ephemeral-environments:environment:preview"
        gh-preview-env-immutable = "repo:nimat-dev@183449925/ephemeral-environments@1392951147:environment:preview"
      }
    }
  }
}

module "repo" {
  source   = "../../modules/repo-onboarding"
  for_each = local.repos

  repository         = each.value.repository
  app                = each.key
  display_name       = each.value.display_name
  image_name         = each.value.image_name
  preview_domain     = each.value.preview_domain
  federated_subjects = each.value.federated_subjects
  subscription_id    = "1325f79b-c2c1-437c-a8c7-a0746ab748d4"
  cluster = {
    id                  = module.team_cluster.cluster_id
    name                = module.team_cluster.cluster_name
    resource_group_name = "nimatresourceg"
    acr_id              = module.team_cluster.acr_id
    acr_name            = "nimatpreviewacr"
    acr_login_server    = module.team_cluster.acr_login_server
  }
}

# Flux applies these (clusters/nimat/config → repos/); commit them after apply.
resource "local_file" "repo_guard" {
  for_each        = module.repo
  filename        = "${path.module}/../../../clusters/nimat/config/repos/${each.key}.yaml"
  content         = each.value.guard_manifest
  file_permission = "0644"
}

resource "local_file" "repos_kustomization" {
  filename        = "${path.module}/../../../clusters/nimat/config/repos/kustomization.yaml"
  file_permission = "0644"
  content = join("\n", concat([
    "# GENERATED by platform/envs/nimat/repos.tf (F020) — one guard file per onboarded repo.",
    "apiVersion: kustomize.config.k8s.io/v1beta1",
    "kind: Kustomization",
    "resources:",
  ], [for k in sort(keys(local.repos)) : "  - ${k}.yaml"], [""]))
}

output "repos" {
  value = { for k, m in module.repo : k => { client_id = m.client_id, principal_object_id = m.principal_object_id } }
}
